# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "mpt3sas" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "zfs" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "zfs" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.kernelParams = [
    "pcie_aspm=force"
    "intel_pstate=enable"
    "intel_idle.max_cstate=9"
    "intel_idle.preferred_cstates=6"
    "nvme_core.default_ps_max_latency_us=15000"
    "nmi_watchdog=0"
    "modprobe.blacklist=i915"
  ];
  # power saving options for intel uhd graphic
  boot.extraModprobeConfig = ''
    options i915 enable_dc=2 enable_fbc=1 enable_psr=1 enable_ips=1
    options mpt3sas power_management=1
  '';
  boot.kernel.sysctl = {
    "fs.file-max" = 1000000000;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/effa3081-6a1b-484f-b4ee-c63827ca6f3c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AC7C-5082";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data" = {
    device = "data";
    fsType = "zfs";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/418def0e-b26c-488f-89af-f95196c68003"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  networking.hostId = "f8255735";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
